name: Lint Codebase

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v6
              with:
                  fetch-depth: 1
                  repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
                  ref: ${{ github.head_ref || github.ref }}

            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version: '24'
                  package-manager-cache: false

            - name: Install dependencies
              run: npm install --no-audit --no-fund

            - name: Run JS Lint
              run: npm run lint:js -- --fix
              continue-on-error: true

            - name: Run CSS Lint
              run: npm run lint:css -- --fix
              continue-on-error: true

            - name: Format with Prettier
              run: npm run format
              continue-on-error: true

            - name: Run HTML Lint
              run: npm run lint:html
